### ISSUE TITLE
是否可以可以增加一些语音列表呢

### ISSUE THREAD

**Issue by y1713375484** [linshenkx/edge-tts-openai-cf-worker#1]
感谢作者的作品，部署的cf上非常易于使用，能否再增加一些中午的语音列表支持呢

**Comment by linshenkx** [comment]
> 感谢作者的作品，部署的cf上非常易于使用，能否再增加一些中午的语音列表支持呢

已增加示例及文档说明，本质上只是微软tts的包装，它支持的就都支持

**Comment by y1713375484** [comment]
> > 感谢作者的作品，部署的cf上非常易于使用，能否再增加一些中午的语音列表支持呢
> 
> 已增加示例及文档说明，本质上只是微软tts的包装，它支持的就都支持

好的，感谢
